import { useState } from "react";
import { FaArrowLeft, FaBoxOpen, FaSave } from "react-icons/fa";
import { IoMenu } from "react-icons/io5";
import { toast } from "react-toastify";

const API = "https://app.accionporcolombia.com/servicesPae/Inventario/Embalajes/";
const inicial = { productoBase: "", presentacion: "", embalaje: "", uniCaja: "", estado: 1 };
const leerJson = async (respuesta) => { const texto = await respuesta.text(); try { return JSON.parse(texto); } catch { throw new Error("El servidor devolvió una respuesta inválida."); } };

export const FormularioEmbalajeInventario = ({ setSidebar, navegar, editar = false }) => {
  const seleccionado = (() => { try { return JSON.parse(localStorage.getItem("embalajeInventarioEditar") || "null"); } catch { return null; } })();
  const [formulario, setFormulario] = useState(editar && seleccionado ? { id: seleccionado.id, productoBase: seleccionado.productoBase || "", presentacion: seleccionado.presentacion || "", embalaje: seleccionado.embalaje || "", uniCaja: seleccionado.uniCaja || "", estado: Number(seleccionado.estado) } : inicial);
  const [guardando, setGuardando] = useState(false);
  const actualizar = (evento) => setFormulario((actual) => ({ ...actual, [evento.target.name]: evento.target.name === "estado" ? Number(evento.target.value) : evento.target.value }));
  const guardar = async (evento) => { evento.preventDefault(); if (guardando) return; if (formulario.productoBase.trim().length < 2 || !/^\d+(?:[.,]\d{1,3})?$/.test(formulario.uniCaja.trim())) { toast.error("Indica un producto base y unas unidades por caja válidas."); return; } setGuardando(true); try { const respuesta = await fetch(`${API}InventarioEmbalajesGuardar.php`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...formulario, productoBase: formulario.productoBase.trim(), presentacion: formulario.presentacion.trim(), embalaje: formulario.embalaje.trim(), uniCaja: formulario.uniCaja.trim() }) }); const json = await leerJson(respuesta); if (!respuesta.ok || json.rpta !== "si") throw new Error(json.mensaje); if (editar) localStorage.removeItem("embalajeInventarioEditar"); toast.success(json.mensaje); navegar("EmbalajesInventario"); } catch (error) { toast.error(error.message || "No fue posible guardar el embalaje."); } finally { setGuardando(false); } };
  return <div className="min-h-screen w-full bg-slate-100 p-3 md:p-6"><div className="mx-auto max-w-4xl"><div className="mb-5 flex items-center gap-4"><button type="button" onClick={() => setSidebar(true)} className="rounded-xl border border-slate-200 bg-white p-2.5 md:hidden"><IoMenu /></button><button type="button" onClick={() => navegar("EmbalajesInventario")} className="rounded-xl border border-slate-300 bg-white p-2.5 text-slate-700 hover:bg-slate-100"><FaArrowLeft /></button><div><h1 className="text-xl font-black text-slate-900">{editar ? "Editar embalaje" : "Crear embalaje"}</h1><p className="text-sm text-slate-500">Define la presentación y cantidad de unidades por caja.</p></div></div><form onSubmit={guardar} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="flex items-center gap-3 border-b border-slate-200 px-5 py-4"><div className="rounded-xl bg-blue-50 p-3 text-blue-800"><FaBoxOpen /></div><div><h2 className="font-black text-slate-900">Información del embalaje</h2><p className="text-sm text-slate-500">Los campos marcados son necesarios para los cálculos PAC y UND.</p></div></header><div className="grid gap-5 p-5 md:grid-cols-2"><Campo etiqueta="Producto base *"><input name="productoBase" value={formulario.productoBase} onChange={actualizar} maxLength="180" required placeholder="Ej. AVENA INSTANTÁNEA" /></Campo><Campo etiqueta="Unidades por caja *"><input name="uniCaja" value={formulario.uniCaja} onChange={actualizar} inputMode="decimal" maxLength="50" required placeholder="Ej. 48" /></Campo><Campo etiqueta="Presentación"><input name="presentacion" value={formulario.presentacion} onChange={actualizar} maxLength="120" placeholder="Ej. B X 200 G" /></Campo><Campo etiqueta="Empaque"><input name="embalaje" value={formulario.embalaje} onChange={actualizar} maxLength="180" placeholder="Ej. PACA X 48 BOLSAS" /></Campo><Campo etiqueta="Estado"><select name="estado" value={formulario.estado} onChange={actualizar}><option value="1">Activo</option><option value="0">Inactivo</option></select></Campo></div><footer className="flex flex-col-reverse gap-3 border-t border-slate-200 bg-slate-50 px-5 py-4 sm:flex-row sm:justify-end"><button type="button" disabled={guardando} onClick={() => navegar("EmbalajesInventario")} className="rounded-xl border border-slate-300 bg-white px-5 py-2.5 font-semibold text-slate-700">Cancelar</button><button disabled={guardando} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-800 px-5 py-2.5 font-semibold text-white hover:bg-blue-900 disabled:opacity-60"><FaSave />{guardando ? "Guardando..." : editar ? "Guardar cambios" : "Crear embalaje"}</button></footer></form></div></div>;
};
const Campo = ({ etiqueta, children }) => <label className="block"><span className="mb-1.5 block text-sm font-bold text-slate-700">{etiqueta}</span>{typeof children === "object" ? <div className="[&>input,&>select]:h-11 [&>input,&>select]:w-full [&>input,&>select]:rounded-xl [&>input,&>select]:border [&>input,&>select]:border-slate-300 [&>input,&>select]:px-3 [&>input,&>select]:text-sm [&>input,&>select]:outline-none [&>input,&>select]:focus:border-blue-800 [&>input,&>select]:focus:ring-2 [&>input,&>select]:focus:ring-blue-100">{children}</div> : children}</label>;
